### ISSUE TITLE
Upstream this repo

### ISSUE THREAD

**Issue by retr0h** [openstack-ansible/openstack-ansible-modules#40]
Why isn't this work being merged into the ansible core modules[1]?  Seems like this repo could be used to prototype functionality, then pull requests created to update upstream with the added functionality. IMO this segregation is not benefiting ansible as a whole.

[1] https://github.com/ansible/ansible-modules-core

**Comment by lorin** [comment]
More inertia than anything else. I'm not currently working on OpenStack-related work, and so I don't currently have the cycles to push these upstream. I would be more than happy if somebody else wanted to take the initiative and upstream some modules so they could be removed from here.

@emonty maintains the upstream modules, he may have some additional insight here.

**Comment by emonty** [comment]
Yes, I would love to pull in the functionality into upstream ansible, and I agree that the segregation is not helpful. The openstack modules in ansible-modules-core are deprecated, so the work from in here will want to come in as a follow on to ansible/ansible-modules-extras#92

**Comment by retr0h** [comment]
@emonty @lorin I wouldn't mind taking on that work if you guys are okay with it. I would imagine this repo is fairly mature at this point, and not under heavy development, which would impede it's usefulness.  Now might be a good time to synchronize upstream.

**Comment by lorin** [comment]
@retr0h Works for me. Yes, the code is very stable at this point.

Once a module makes it upstream, just submit a PR here to get it deleted from this repo.

**Comment by emonty** [comment]
@retr0h sweet. So - in general, most of these cover things that are not covered by the current outstanding modules, so that's good. In addition to ansible/ansible-modules-extras#92 you should be aware of the features/openstack-neutron, features/openstack-ironic branches and features/keystone-user branches in emontyansible-modules-extras.

Main things that'll need done are:
 - rename most of them to have an os_ prefix. The rubric there is that a thing that an end user might want to do, like floating_ip, should be called os_floating_ip (there is already one of those in 92, but it might need to be updated) Things that only an admin might want to do, like adding a service to keystone, should be os_keystone_server
 - Port to use openstack_full_argument_list and to use shade to get the client objects at minimum. We've been putting actual openstack-related logic in shade and leaving the ansible modules as a place to deal with ansible workflow logic, but that's impl guts and is not important for a first pass. Using the same auth parameters/shade/os-client-config for parameter processing is.

Obviously, those indicate interface changes from what's in here already - which maens the PR to remove the module from here will probably want to to also update the consuming roles to match the signature updates.

Looking forward to it!
